name: Generate Windows Packages (Debug)

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  generate-windows-installer:
    name: Generate Windows Packages (Debug)
    runs-on: windows-latest

    steps:
    - name: Git Checkout ${{github.event.release.tag_name}}
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Set version number for PyInstaller
      run: |
        python.exe tools\windows-installer\generate-version-info.py ${{github.event.release.tag_name}} debug

    - name: Run PyInstaller to create binaries
      run: |
        pyinstaller.exe --noconfirm turing-system-monitor-debug.spec
        "${{github.event.release.tag_name}}-debug" | Out-File ".\dist\turing-system-monitor\version.txt"

    - name: Create InnoSetup installer from generated binaries
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.6
      with:
        path: tools/windows-installer/turing-system-monitor.iss
        options: /O+

    - name: Create portable zip archive from generated binaries
      run: |
        Remove-Item -r ".\dist\turing-system-monitor\res\themes\--Theme examples\"
        7z a -tzip turing-system-monitor-${{github.event.release.tag_name}}-portable-debug.zip ".\dist\turing-system-monitor"

    - name: 'ðŸ“¦ Archive Windows installer'
      uses: actions/upload-artifact@v4
      with:
        name: turing-system-monitor-${{github.event.release.tag_name}}-debug
        path: tools\windows-installer\Output\turing-system-monitor-${{github.event.release.tag_name}}-debug.exe
        if-no-files-found: error

    - name: 'ðŸ“¦ Archive Windows portable archive'
      uses: actions/upload-artifact@v4
      with:
        name: turing-system-monitor-${{github.event.release.tag_name}}-portable-debug
        path: turing-system-monitor-${{github.event.release.tag_name}}-portable-debug.zip
        if-no-files-found: error

    - name: 'ðŸ“© Publish Windows installer to Release'
      run: |
        gh release upload ${{github.event.release.tag_name}} tools\windows-installer\Output\turing-system-monitor-${{github.event.release.tag_name}}-debug.exe
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 'ðŸ“© Publish Windows portable zip to Release'
      run: |
        gh release upload ${{github.event.release.tag_name}} turing-system-monitor-${{github.event.release.tag_name}}-portable-debug.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
